### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.ao.quantization'

### ISSUE THREAD

**Issue by chuckie82** [harshit-gupta-cor/XFELPoseGAN#1]
Runtime error on SDF following `conda env create --file environment.yml`

(xfel) [yoon82@sdf-login01 XFELPoseGAN]$ python main.py config_path configs/xfel_splice_simulated_poses_supervised_multires.yaml
```bash
/scratch/y/yoon82/XFELPoseGAN/ml_modules.py:688: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(len(feature_channels)>0,
/scratch/y/yoon82/XFELPoseGAN/ml_modules.py:871: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(len(feature_channels)>0,
/scratch/y/yoon82/XFELPoseGAN/ml_modules.py:1034: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(len(feature_channels)>0,
/sdf/home/y/yoon82/miniconda3/envs/xfel/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /sdf/home/y/yoon82/miniconda3/envs/xfel/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZNK2at10TensorBase21__dispatch_contiguousEN3c1012MemoryFormatE
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/scratch/y/yoon82/XFELPoseGAN/main.py", line 10, in <module>
    from wrapper import SupervisedXFELposeganWrapper
  File "/scratch/y/yoon82/XFELPoseGAN/wrapper.py", line 1, in <module>
    from supervised_xfelposegan import XFELPoseGAN
  File "/scratch/y/yoon82/XFELPoseGAN/supervised_xfelposegan.py", line 7, in <module>
    from writer_utils import writer_image_add_dict, writer_update_weight, dict_from_dis, dict_from_gen, norm_of_weights, writer_scalar_add_dict
  File "/scratch/y/yoon82/XFELPoseGAN/writer_utils.py", line 1, in <module>
    import torchvision
  File "/sdf/home/y/yoon82/miniconda3/envs/xfel/lib/python3.9/site-packages/torchvision/__init__.py", line 7, in <module>
    from torchvision import models
  File "/sdf/home/y/yoon82/miniconda3/envs/xfel/lib/python3.9/site-packages/torchvision/models/__init__.py", line 18, in <module>
    from . import quantization
  File "/sdf/home/y/yoon82/miniconda3/envs/xfel/lib/python3.9/site-packages/torchvision/models/quantization/__init__.py", line 3, in <module>
    from .mobilenet import *
  File "/sdf/home/y/yoon82/miniconda3/envs/xfel/lib/python3.9/site-packages/torchvision/models/quantization/mobilenet.py", line 1, in <module>
    from .mobilenetv2 import *  # noqa: F401, F403
  File "/sdf/home/y/yoon82/miniconda3/envs/xfel/lib/python3.9/site-packages/torchvision/models/quantization/mobilenetv2.py", line 6, in <module>
    from torch.ao.quantization import QuantStub, DeQuantStub
ModuleNotFoundError: No module named 'torch.ao.quantization'
```

**Comment by chuckie82** [comment]
this works:
```python
from torch.quantization import QuantStub, DeQuantStub
```
but need a cleaner fix
